Natasha/listening
cuappdev/podcast-ios pull request #403
Opened 2018-04-13 21:32 UTC by natashaarmbrust

- add "Jump Back In" feature in `BookmarkViewController`
- add dismissing Facebook friends 

Right now I'm waiting on backend for the full jump back in feature integration. The UI works now it just doesn't show actually dismiss when you refresh the view.

2018-04-14 17:16 UTC, doctor3w requested changes
Just a few naming things!

2018-04-14 17:16 UTC, doctor3w commented on Podcast/BookmarkViewController.swift
> +    func continueListeningCollectionViewCellDismissButtonPress(cell: ContinueListeningCollectionViewCell) {
dismissButtonPressed(on continueListeningCell: ..)

2018-04-14 17:16 UTC, drewsdunne commented on Podcast/ContinueListeningCollectionViewCell.swift
> +    func continueListeningCollectionViewCellDismissButtonPress(cell: ContinueListeningCollectionViewCell)
like I said above.

2018-04-14 17:16 UTC, drewsdunne commented on Podcast/FacebookFriendsTableViewCell.swift
> +    func facebookFriendsTableViewCellDidPressDismissButton(tableViewCell: FacebookFriendsTableViewCell, collectionViewCell: FacebookFriendsCollectionViewCell, indexPath: IndexPath)
haha maybe change all these too if you get the chance. 
facebookFriendsTableView(didPress action: [NEW_ACTION_ENUM], on cell: CellType)
something like that. Can make the actions into an enum, makes it easy to add actions. 
Or at least rename and keep separate.

2018-04-15 16:39 UTC, mindylou commented on Podcast/ContinueListeningCollectionViewCell.swift
> +            timeLeftLabel.text = "\(minsLeft) min left"
what if there are hours left?

2018-04-15 16:39 UTC, mindylou commented on Podcast/DismissFacebookFriendEndpointRequest.swift
> +        print(json)
remove print

2018-04-15 16:39 UTC, mindylou commented on Podcast/FacebookFriendsCollectionViewCell.swift
> +        dismissButton.imageEdgeInsets = UIEdgeInsets.zero
you can do `.zero` here

2018-04-15 16:39 UTC, mindylou commented on Podcast/ContinueListeningCollectionViewCell.swift
> +            timeLeftLabel.text = "\(minsLeft) min left"
![image](https://user-images.githubusercontent.com/20246620/38780782-d6b281bc-40a9-11e8-83ee-f75c9a296306.png)
![image](https://user-images.githubusercontent.com/20246620/38780783-d8f4e316-40a9-11e8-9a81-7185e740ab38.png)
I don't think these are matching up based on the episode current progress

2018-04-26 19:40 UTC, merged