started new project for redesign
cuappdev/podcast-ios pull request #434
Opened 2018-09-13 00:24 UTC by drewsdunne

Yup here is the base new one. Only SnapKit install. Go wild.

2018-09-13 00:30 UTC, drewsdunne commented
The best refactor yet

2018-09-13 00:32 UTC, mindylou requested changes
Two quick changes otherwise it looks good!

2018-09-13 00:32 UTC, mindylou commented on Recast/AppDelegate.swift
> +        let nc = UINavigationController(rootViewController: seriesViewControllerTest)
can you name this variable better? even though it's gonna be replaced later just for style conventions

2018-09-13 00:32 UTC, mindylou commented on old/Podcast/Keys.plist
> +<?xml version="1.0" encoding="UTF-8"?>
aaaaa remove this!

2018-09-14 13:47 UTC, drewsdunne commented
All fixed!

2018-09-14 15:01 UTC, merged