Jack/episodes+player
cuappdev/podcast-ios pull request #438
Opened 2018-09-18 18:13 UTC by jackthmp

Created **very basic** SeriesDetailView and collapsable player. Player is copied from old app version, without the episode info (hence all of the constants from previous design)

Closes #431

2018-09-18 20:39 UTC, mindylou requested changes
Some small (but tedious) style changes otherwise looks good! I'll approve once those are fixed

2018-09-18 20:39 UTC, mindylou commented on Recast/EpisodeTableViewCell.swift
> +    /// MARK: Variables
Can you change these to `// MARK: - ` so they're accessible from the top bar

2018-09-18 20:39 UTC, mindylou commented on Recast/EpisodeTableViewCell.swift
> +        episodeNameLabel.font = UIFont.systemFont(ofSize: 16)
remove `UIFont.`

2018-09-18 20:39 UTC, mindylou commented on Recast/EpisodeTableViewCell.swift
> +        dateTimeLabel.font = UIFont.systemFont(ofSize: 12)
here too

2018-09-18 20:39 UTC, mindylou commented on Recast/EpisodeTableViewCell.swift
> +        episodeDescriptionView.font = UIFont.systemFont(ofSize: 14)
same here

2018-09-18 20:39 UTC, mindylou commented on Recast/EpisodeTableViewCell.swift
> +        episodeImageView.snp.makeConstraints { (make) in
remove parentheses around `(make)` for all of the snapkit methods

2018-09-18 20:39 UTC, mindylou commented on Recast/PlayerHeaderView.swift
> +    let playerHeaderViewHeight: CGFloat = 55
add `// MARK: - ` variables/constants for this file too

2018-09-18 20:39 UTC, mindylou commented on Recast/PlayerControlsView.swift
> +    let sliderHeight: CGFloat = 1.5
Can you add a `// MARK: - Variables` and `// MARK: - Constants` here?

2018-09-18 20:39 UTC, mindylou commented on Recast/PlayerViewController.swift
> +    /// MARK: Variables
change these to `// MARK: -`

2018-09-18 20:39 UTC, mindylou commented on Recast/PlayerViewController.swift
> +        playerHeaderView.snp.makeConstraints { (make) in
remove parentheses around `(make)` here too

2018-09-18 20:39 UTC, mindylou commented on Recast/PlayerViewController.swift
> +    /// MARK: PlayerHeaderViewDelegate
make delegates extensions of the view controller and use `// MARK: -`

2018-09-18 20:39 UTC, mindylou commented on Recast/SeriesHeaderView.swift
> +    /// MARK: Variables
change these here too to `// MARK: -`

2018-09-18 20:39 UTC, mindylou commented on Recast/SeriesHeaderView.swift
> +        imageView.snp.makeConstraints { (make) in
remove parentheses

2018-09-18 20:39 UTC, mindylou commented on Recast/SeriesViewController.swift
> +    /// MARK: Variables
same thing here

2018-09-18 20:39 UTC, mindylou commented on Recast/SeriesViewController.swift
> +        headerView.snp.makeConstraints { (make) in
remove parentheses here

2018-09-18 20:39 UTC, mindylou commented on Recast/SeriesViewController.swift
> +///MARK: episodeTableView Delegate & DataSource
Can you separate these out into delegate and data source extensions? Use `// MARK - `

2018-09-19 01:47 UTC, mindylou submitted a review, later dismissed

2018-09-19 21:39 UTC, doctor3w requested changes

2018-09-19 21:39 UTC, drewsdunne commented on Recast/EpisodeTableViewCell.swift
> +    let padding = 5
Move these to the layoutSubviews function

2018-09-19 21:39 UTC, drewsdunne commented on Recast/PlayerControlsView.swift
> +    let sliderHeight: CGFloat = 1.5
move all these to layoutSubviews()

2018-09-19 21:39 UTC, drewsdunne commented on Recast/PlayerHeaderView.swift
> +    let playerHeaderViewHeight: CGFloat = 55
again move these

2018-09-19 21:39 UTC, drewsdunne commented on Recast/PlayerViewController.swift
> +    let topPadding: CGFloat = 100
here too

2018-09-19 21:39 UTC, drewsdunne commented on Recast/SeriesHeaderView.swift
> +    let imageHeight = 100
these too

2018-09-19 21:39 UTC, drewsdunne commented on Recast/SeriesViewController.swift
> +    let headerHeight: CGFloat = 200
move this

2018-09-19 21:39 UTC, drewsdunne commented on Recast/SeriesViewController.swift
> +    let reuseIdentifer = "episodeCell"
better name for this variable

2018-09-19 21:42 UTC, mindylou approved these changes

2018-09-19 21:42 UTC, doctor3w approved these changes

2018-09-19 21:43 UTC, merged