Jack/discover2
cuappdev/podcast-ios pull request #443
Opened 2018-09-26 22:34 UTC by jackthmp

- Implements discover designs
- Adds search bar, podcast cells, search results view
- Adds KingFisher pod for downloading images

2018-09-26 22:45 UTC, mindylou reviewed
Small changes but otherwise looks good

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/DiscoverTableViewHeader.swift
> +        subscribeButton.backgroundColor = #colorLiteral(red: 0.2823529412, green: 0.6117647059, blue: 0.5960784314, alpha: 1)
change this to zeplin's color later (I think @jaewonsim made a constant for it)

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/DiscoverTableViewHeader.swift
> +        seeMoreButton.setTitle("see more", for: .normal)
change this to "See more"

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/DiscoverTableViewHeader.swift
> +
delete newline

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/DiscoverViewController.swift
> +            //it was all in the console. It told me the height was ambigious
you can delete this comment from austin lol

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/MainSearchDataSourceDelegate.swift
> +            .success { (response: SearchResults) in
you can just do `response in`

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/MainSearchDataSourceDelegate.swift
> +            .failure { (error: Error) in
`error in`

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/MainSearchViewController.swift
> +
delete newline

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/MainSearchViewController.swift
> +
delete newline

2018-09-26 22:45 UTC, mindylou commented on Recast/Discover/MainSearchDataSourceDelegate.swift
> +extension MainSearchDataSourceDelegate: UITableViewDataSource {
Add `// MARK:` for these

2018-09-28 00:36 UTC, mindylou submitted a review, later dismissed
Remember to run swiftlint autocorrect but otherwise lgtm

2018-09-28 00:36 UTC, mindylou commented on Recast/AppDelegate.swift
> +
make sure to run `swiftlint autocorrect`!

2018-09-28 00:36 UTC, mindylou commented on Recast/Discover/MainSearchDataSourceDelegate.swift
> +
Also add a `// MARK` for here

2018-09-28 14:31 UTC, doctor3w requested changes

2018-09-28 14:31 UTC, drewsdunne commented on PreviewPlayerView.swift
> +    private var upNextLabel: UILabel!
No need to make these private, let's leave these public until we know for sure how it'll interact with our player and view controller.

2018-09-28 14:31 UTC, drewsdunne commented on Recast/Cells/PodcastTableViewCell.swift
> +        super.layoutSubviews()
don't need this do we?

2018-09-28 14:31 UTC, drewsdunne commented on Recast/Discover/MainSearchDataSourceDelegate.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: PodcastTableViewCell.cellReuseIdentifier, for: indexPath)
You should be able to just force cast this, shouldn't have to safely fall to a blank cell

2018-09-28 14:31 UTC, drewsdunne commented on Recast/Discover/MainSearchDataSourceDelegate.swift
> +        let artworkURL = podcast.artworkUrl600 ?? podcast.artworkUrl100 ?? podcast.artworkUrl60 ?? podcast.artworkUrl30
dat chaining tho!

2018-09-28 14:31 UTC, drewsdunne commented on Recast/Discover/MainSearchViewController.swift
> +        searchResultsTableView.register(PodcastTableViewCell.self, forCellReuseIdentifier: PodcastTableViewCell.cellReuseIdentifier)
You could probably decrease this line length by pulling PodcastTableViewCell.cellReuseIdentifier out into a `let = reuseId = ...`

Better than ignoring the convention

2018-09-28 14:31 UTC, drewsdunne commented on Recast/PlayerControlsView.swift
> +    //swiftlint:disable:next function_body_length
space after `//`

2018-09-28 14:31 UTC, drewsdunne commented on Recast/SeriesViewController.swift
>          return EpisodeTableViewCell(style: .default, reuseIdentifier: episodeCellReuseIdentifer)
dequeue?

2018-09-28 14:31 UTC, drewsdunne commented on Recast/iTunesPodcasts/iTunesSearch/Models.swift
> +    let contentAdvisoryRating: String?
Is this not always there? Interesting...

2018-09-28 15:17 UTC, doctor3w approved these changes

2018-09-28 15:17 UTC, doctor3w approved these changes

2018-09-28 15:18 UTC, merged