Replace home screen's UITableView to UICollectionView
cuappdev/podcast-ios pull request #448
Opened 2018-10-24 22:52 UTC by jaewonsim

- Replaces home screen's UITableView to UICollectionView
- Updates layout for homeCollectionView accordingly
- Fix minor UI mistakes in home screen's sub-UICollectionViews' cells

2018-10-25 02:05 UTC, mindylou requested changes
great work so far!! just a couple of comments and suggested changes

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +    /// - Returns: The HomeSubsection for the corresponding tag or section
wow this documentation is next level 👌

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +    func isLastSection(section: Int) -> Bool {
```suggestion
    func isLastSection(_ section: Int) -> Bool {
```

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +            return CGSize.zero
```suggestion
            return .zero
```

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +        let subCollectionViewSectionInset = UIEdgeInsets(top: 0, left: 22, bottom: 0, right: 22)
consider keeping a constant in this function with the left + right insets

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +            return UIEdgeInsets.zero
```suggestion
            return .zero
```

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +        } else {
```suggestion
```

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +            } else {
```suggestion
```

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +        } else {
```suggestion
```

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +        } else {
```suggestion
```

2018-10-25 02:05 UTC, mindylou commented on Recast/HomeViewController.swift
> +            assert(false)
not sure if we want an assert here bc it'll break the app, maybe return an empty `UICollectionReusableView`?

2018-10-26 01:07 UTC, doctor3w reviewed
This looks awesome! Great work! Just a few questions!

2018-10-26 01:07 UTC, drewsdunne commented on Recast/Cells/HomeContinueListeningCollectionViewCell.swift
> +    override init(frame: CGRect) {
Does CollectionViewCell not have a reuseIdentifier init? If it does we should use that.

2018-10-26 01:07 UTC, drewsdunne commented on Recast/Cells/HomePodcastGridCollectionViewCell.swift
> +    override init(frame: CGRect) {
Same here

2018-10-26 01:07 UTC, drewsdunne commented on Recast/HomeViewController.swift
> +        let type = HomeSubsection.homeSubsection(for: .tag, value: collectionView.tag)!
Does this cause swiftlint warnings?

2018-10-26 17:48 UTC, mindylou submitted a review, later dismissed

2018-10-28 16:45 UTC, jackthmp submitted a review, later dismissed

2018-10-28 16:45 UTC, jackthmp commented on Recast/HomeViewController.swift
> +    var homeCollectionViewSection: Int? {
I feel like this can be replaced with using HomeSubsection.allCases

2018-10-29 15:22 UTC, mindylou approved these changes

2018-10-29 20:40 UTC, jackthmp approved these changes

2018-10-29 20:53 UTC, merged